/**
 * @fileoverview platform-users API Route - Proxy to NestJS API
 * 
 * ✅ ARCHITECTURE COMPLIANCE: This route now proxies to NestJS API
 * All business logic, permissions, and database access are handled by NestJS
 * 
 * @generated by fix-api-routes.sh
 */

import { NextRequest } from 'next/server';
import { proxyGET, proxyPOST, proxyPUT, proxyPATCH, proxyDELETE } from '@/lib/api-proxy';

{{METHODS}}
