module.exports = {
  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        {type: 'autogenerated', dirName: 'getting-started'}
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        {type: 'autogenerated', dirName: 'architecture'}
      ],
    },
    {
      type: 'category',
      label: 'Features',
      items: [
        {type: 'autogenerated', dirName: 'features'}
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        {type: 'autogenerated', dirName: 'api-reference'}
      ],
    },
    {
      type: 'category',
      label: 'Development',
      items: [
        {type: 'autogenerated', dirName: 'development'}
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      items: [
        {type: 'autogenerated', dirName: 'deployment'}
      ],
    },
    {
      type: 'category',
      label: 'Testing',
      items: [
        {type: 'autogenerated', dirName: 'testing'}
      ],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      items: [
        {type: 'autogenerated', dirName: 'troubleshooting'}
      ],
    },
  ],
};