import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Custom sidebar reflecting the 5-tier architecture
  tutorialSidebar: [
    'README',
    {
      type: 'category',
      label: '📦 Installation',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'installation',
        },
      ],
    },
    {
      type: 'category',
      label: '🌐 Platform Tier',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'platform',
        },
      ],
    },
    {
      type: 'category',
      label: '🏢 Tenant Tier',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'tenant',
        },
      ],
    },
    {
      type: 'category',
      label: '👥 Account Tier',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'account',
        },
      ],
    },
    {
      type: 'category',
      label: '👤 User Tier',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'user',
        },
      ],
    },
    {
      type: 'category',
      label: '🌍 Public Tier',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'public',
        },
      ],
    },
    {
      type: 'category',
      label: '🏗️ Architecture',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'architecture',
        },
      ],
    },
    {
      type: 'category',
      label: '⚙️ Development',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'development',
        },
      ],
    },
    {
      type: 'category',
      label: '📖 Reference',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'reference',
        },
      ],
    },
  ],
};

export default sidebars;
