/**
 * @fileoverview Media Upload (Optimized) API Route - Proxy to NestJS API
 * 
 * ✅ ARCHITECTURE COMPLIANCE: This route now proxies to NestJS API
 * All business logic, permissions, and database access are handled by NestJS
 * 
 * @generated by fix
 */

import { NextRequest } from 'next/server';
import { proxyPOST } from '@/lib/api-proxy';

/**
 * POST /api/media/upload
 * Proxy to NestJS POST /api/media/upload
 */
export async function POST(request: NextRequest) {
  return proxyPOST(request);
}