# Prometheus Configuration for Mono Platform
# Fixed configuration with correct service targets and metrics endpoints

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'mono-platform'

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 10s

  # Node Exporter - System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    scrape_timeout: 10s

  # cAdvisor - Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    scrape_timeout: 10s

  # RabbitMQ metrics (Prometheus plugin enabled)
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Temporal metrics
  - job_name: 'temporal'
    static_configs:
      - targets: ['temporal:9091']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # PostgreSQL metrics (if postgres_exporter is running)
  # Note: Currently no postgres_exporter, but prepared for future
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']
  #   scrape_interval: 30s

  # Redis metrics (if redis_exporter is running)
  # Note: Currently no redis_exporter, but prepared for future
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']
  #   scrape_interval: 30s

  # FastAPI API metrics (when available)
  # - job_name: 'fastify-api'
  #   static_configs:
  #     - targets: ['api:3001']
  #   metrics_path: '/metrics'
  #   scrape_interval: 15s

  # Next.js frontend metrics (when available)
  # - job_name: 'nextjs-web'
  #   static_configs:
  #     - targets: ['web:3000']
  #   metrics_path: '/api/metrics'
  #   scrape_interval: 30s

# Alertmanager configuration (when implemented)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093