groups:
  - name: mono-platform
    rules:
      # API Health
      - alert: MonoAPIDown
        expr: up{job="mono-api"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "itellico Mono API is down"
          description: "The itellico Mono API has been down for more than 1 minute."

      # Frontend Health
      - alert: MonoFrontendDown
        expr: up{job="mono-frontend"} == 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "itellico Mono Frontend is down"
          description: "The itellico Mono Frontend has been down for more than 2 minutes."

      # High CPU Usage
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for more than 5 minutes."

      # High Memory Usage
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is above 85% for more than 5 minutes."

      # Container Monitoring Down
      - alert: ContainerMonitoringDown
        expr: up{job="cadvisor"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Container monitoring is down"
          description: "cAdvisor container monitoring has been down for more than 1 minute."

      # Node Exporter Down
      - alert: NodeExporterDown
        expr: up{job="node-exporter"} == 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Node Exporter is down"
          description: "Node Exporter system monitoring has been down for more than 2 minutes."

      # PostgreSQL Down (simplified check)
      - alert: PostgreSQLDown
        expr: up{job="cadvisor"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "PostgreSQL monitoring unavailable"
          description: "PostgreSQL container monitoring is unavailable (cAdvisor down)."

      # Temporal Down (simplified check)
      - alert: TemporalDown
        expr: up{job="cadvisor"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Temporal monitoring unavailable"
          description: "Temporal container monitoring is unavailable (cAdvisor down)."

      # Redis Down (simplified check)
      - alert: RedisDown
        expr: up{job="cadvisor"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Redis monitoring unavailable"
          description: "Redis container monitoring is unavailable (cAdvisor down)."

      # RabbitMQ Health
      - alert: RabbitMQDown
        expr: up{job="rabbitmq"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "RabbitMQ is down"
          description: "RabbitMQ message queue has been down for more than 1 minute."

      # High RabbitMQ Memory Usage
      - alert: RabbitMQHighMemoryUsage
        expr: (rabbitmq_process_resident_memory_bytes / rabbitmq_resident_memory_limit_bytes) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "RabbitMQ high memory usage"
          description: "RabbitMQ memory usage is above 80% for more than 5 minutes."

      # High Queue Message Count
      - alert: RabbitMQHighQueueMessages
        expr: sum(rabbitmq_queue_messages) > 1000
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "RabbitMQ high queue message count"
          description: "RabbitMQ has more than 1000 messages in queues for more than 10 minutes."

      # No Consumers Available
      - alert: RabbitMQNoConsumers
        expr: rabbitmq_queue_consumers == 0 and rabbitmq_queue_messages > 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "RabbitMQ has no consumers"
          description: "RabbitMQ has messages in queues but no consumers available for more than 5 minutes."

      # Low Disk Space
      - alert: RabbitMQLowDiskSpace
        expr: (rabbitmq_disk_space_available_bytes / (rabbitmq_disk_space_available_bytes + 1000000000)) * 100 < 20
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "RabbitMQ low disk space"
          description: "RabbitMQ available disk space is below 20% for more than 5 minutes."