apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: prometheus-uid
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 5s
      httpMethod: POST
    secureJsonData: {}