#!/bin/bash

echo "🗄️  Redis Database Configuration Guide"
echo "======================================"
echo ""
echo "Redis supports 16 logical databases (0-15). Here's the recommended setup:"
echo ""

echo "📋 Database Assignment Strategy:"
echo "┌──────────────┬─────────────────────────────────────┐"
echo "│ Database #   │ Purpose                             │"
echo "├──────────────┼─────────────────────────────────────┤"
echo "│ 0 (default)  │ Sessions & Authentication           │"
echo "│ 1            │ Application Cache                   │"
echo "│ 2            │ User Permissions & RBAC             │"
echo "│ 3            │ Rate Limiting & Temporary Data      │"
echo "│ 4            │ Queues & Background Jobs            │"
echo "│ 5            │ Feature Flags & Configuration       │"
echo "│ 6            │ Monitoring & Metrics                │"
echo "│ 7            │ Development/Testing                 │"
echo "│ 8-15         │ Reserved for Future Use             │"
echo "└──────────────┴─────────────────────────────────────┘"
echo ""

echo "🔧 RedisInsight Setup - Add Multiple Connections:"
echo ""
echo "Connection 1 - Sessions (Default):"
echo "   Host: localhost"
echo "   Port: 6379"
echo "   Database Index: 0"
echo "   Name: mono-sessions"
echo ""
echo "Connection 2 - Application Cache:"
echo "   Host: localhost"
echo "   Port: 6379"
echo "   Database Index: 1"
echo "   Name: mono-cache"
echo ""
echo "Connection 3 - Permissions:"
echo "   Host: localhost"
echo "   Port: 6379"
echo "   Database Index: 2"
echo "   Name: mono-permissions"
echo ""
echo "Connection 4 - Rate Limiting:"
echo "   Host: localhost"
echo "   Port: 6379"
echo "   Database Index: 3"
echo "   Name: mono-ratelimit"
echo ""

echo "💡 Pro Tips:"
echo "• Start with Database 0 for your main connection"
echo "• Add more databases as needed for organization"
echo "• Each database is completely isolated"
echo "• You can switch between databases in RedisInsight"
echo ""

echo "🚀 Quick Test - Check Database Separation:"
echo "Database 0 keys: $(redis-cli -h localhost -p 6379 -n 0 dbsize)"
echo "Database 1 keys: $(redis-cli -h localhost -p 6379 -n 1 dbsize)"
echo "Database 2 keys: $(redis-cli -h localhost -p 6379 -n 2 dbsize)"
echo ""

echo "🔑 CLI Commands to Switch Databases:"
echo "redis-cli -h localhost -p 6379 -n 0  # Database 0"
echo "redis-cli -h localhost -p 6379 -n 1  # Database 1"
echo "redis-cli -h localhost -p 6379 -n 2  # Database 2"