
import { SubscriptionPlan } from '@/lib/subscription-schema';

export const subscriptionPlans: SubscriptionPlan[] = [
  {
    id: 1,
    planKey: 'free',
    name: 'Free',
    description: 'For individuals and small teams getting started.',
    planType: 'account',
    monthlyPrice: '0',
    yearlyPrice: '0',
    renewPrice: '0',
    yearlyDiscount: 0,
    isActive: true,
    isDefault: true,
    isCustom: false,
    sortOrder: 1,
    trialDays: 0,
    metadata: {},
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    planKey: 'pro',
    name: 'Pro',
    description: 'For growing businesses that need more power and support.',
    planType: 'account',
    monthlyPrice: '99',
    yearlyPrice: '999',
    renewPrice: '99',
    yearlyDiscount: 15,
    isActive: true,
    isDefault: false,
    isCustom: false,
    sortOrder: 2,
    trialDays: 14,
    metadata: {},
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    planKey: 'enterprise',
    name: 'Enterprise',
    description: 'For large organizations with advanced security and support needs.',
    planType: 'tenant',
    monthlyPrice: '999',
    yearlyPrice: '9999',
    renewPrice: '999',
    yearlyDiscount: 20,
    isActive: true,
    isDefault: false,
    isCustom: true,
    sortOrder: 3,
    trialDays: 30,
    metadata: {},
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
